### ISSUE TITLE
Conditionally include relationships

### ISSUE THREAD

**Issue by lleger** [vt-elixir/ja_serializer#232] opened 2017-03-19 22:44 UTC
I have a question about JaSerializer and relationships/including. My understanding of the spec means we can use `include` to optionally include relationships. 

Consider a serializer with this relationship:

```elixir
# post.ex
has_many :comments,
  serializer: MyApp.CommentView,
  include: false,
  identifiers: :when_included
```

If we make a request without the include parameter, this will render a response that looks something like this:

```json
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "post",
    "relationships": {
      "comments": {},
    },
    "id": "174f3a81-5151-4bf1-8d8d-164d59d25375",
    "attributes": {
      "updated-at": "2017-03-17T23:39:20.205508",
      "inserted-at": "2017-03-15T03:48:41.774795",
    }
  }
}
```

This isn't valid JSON API though:

> Resource linkage MUST be represented as one of the following:
> - null for empty to-one relationships.
> - an empty array ([]) for empty to-many relationships.
> - a single resource identifier object for non-empty to-one relationships.
> - an array of resource identifier objects for non-empty to-many relationships.

I _think_ the best solution would be to just remove `relationships` completely (since it's optional), in this case. Setting it to `null` or an empty array doesn't make sense to me, semantically (the relationship isn't empty, we just aren't including it in this response).

Does this make sense or am I misreading the spec? (It is also possible this option already exists in JaSerializer and I missed it.)

**Comment by yogipatel** [comment] 2017-03-20 15:07
I have been wondering the same thing, and just came across it as an issue with one of our front-end clients. Unless this is a regression, I'm surprised more people haven't run into this.

**Comment by alanpeabody** [comment] 2017-03-20 18:25
Totally agree, if the relationship has nothing it it lets remove it completely. A PR would be very welcome!

**Comment by yogipatel** [comment] 2017-03-21 14:48
@alanpeabody Sure, I'll try to check it out in the next few days.

**Comment by darkbaby123** [comment] 2017-03-31 15:25
I think it's not the best solution. The `comments` is actually a relationship object but not a resource linkage. And according to JSON API spec:

> A “relationship object” MUST contain at least one of the following:
> 
> - links: a links object containing at least one of the following:
>   - self: a link for the relationship itself (a “relationship link”). This link allows the client to directly manipulate the relationship. For example, removing an author through an article’s relationship URL would disconnect the person from the article without deleting the people resource itself. When fetched successfully, this link returns the linkage for the related resources as its primary data. (See Fetching Relationships.)
>   - related: a related resource link
> - data: resource linkage
> - meta: a meta object that contains non-standard meta-information about the relationship.

This is my understanding: A relationship is used to describe the relationships between the current resource and other resource. No matter the other resource is empty/null or not, the relationship always exist and doesn't affected by the data. In JaSerializer, as developer defines the relationship with `has_many`, it should exist anyway.

I think a better way to specify a `link` if you don't want to provide the `data`. And the responsibility of JaSerializer is -- it should tell developers to either provide a `link` or `data`.

**Comment by lleger** [comment] 2017-03-31 17:00
My understanding comes from reading [this](http://jsonapi.org/format/#document-resource-objects) section of the spec:

> In addition, a resource object MAY contain any of these top-level members:
> . . .
> - `relationships`: a relationships object describing relationships between the resource and other JSON API resources.

In my head, that means it _can_ include `relationships` but it doesn't have to. The section you pasted applies when _do_ include it. The fact that it's an empty object (`{}`) when you don't include it (like in my example above) is, I don't think, valid. As you pointed out, it should either have the data or not. My request was to allow the removal of what I think is invalid according to the spec; as of now, you have no control over that.

**Comment by yogipatel** [comment] 2017-03-31 17:26
I agree with @lleger's interpretation.

Sorry for the delay, I've been busy with EmberConf. I'll update the PR early next week.

**Comment by darkbaby123** [comment] 2017-04-01 02:50
@lleger I agree with removing empty relationships object because it violates the spec and an empty object doesn't provide any information. After all JSON API just says the `relationships` is optional but not why/when it can be optional. I think it depends on developers choice.

My view of optional `relationships` is simply because there're some kind of resources don't need to define any relationships. The same reason apply to optional `attributes`.

Relationship is a way to _tell the client how to get the related resources_, but it's not the related resources themselves. A post may has no comments, but the relationship between post and comments is always there. My habit is providing a link in this case:

```json
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "type": "post",
    "relationships": {
      "comments": {
        "links": {
          "related": "/posts/1/comments"
        }
      },
    },
    "id": "174f3a81-5151-4bf1-8d8d-164d59d25375",
    "attributes": {
      "updated-at": "2017-03-17T23:39:20.205508",
      "inserted-at": "2017-03-15T03:48:41.774795",
    }
  }
}
```

The benefit is, the client knows the post has comments relationship and also knows how to get/refresh the related comments. Without the `comments` the client doesn't even know such relationship. To get comments for post A, the client can either choose to query comments with filter (if it knows how to query, like `comments?post_id=1`) or reload the post with `/posts/1?include=comments`.

**Comment by lleger** [comment] 2017-04-01 17:23
That makes sense, but seems to me that it's an opinionated implementation. That's not really the point of this issue that I opened.

**Comment by darkbaby123** [comment] 2017-04-02 13:14
@lleger Yes, this is opinionated. Your solution is the best so far. Please go ahead. 😄

**Comment by ryedeer** [comment] 2018-11-08 09:36
Hello! I see that this issue was opened almost two years ago, but the problem with the empty objects in relationships is still there. Does anyone know if there are plans to solve it in this library, or the best way to fix it for now is to patch the PhoenixView using the workaround suggested in #285 ? Thank you in advance!

**Comment by beerlington** [comment] 2018-11-08 11:36
@ryedeer my apologies on the slow timeline for this. We are planning to address it in the library. There was a PR that was opened, but never heard back from the contributor. I'll take a look at finishing it up myself.

**Comment by ryedeer** [comment] 2018-11-08 12:39
@beerlington Thank you very much! We will use the aforementioned workaround for a while, but it would be great if it is handled within the library.

**Comment by beerlington** [comment] 2019-04-02 02:13
Closed in https://github.com/vt-elixir/ja_serializer/pull/311

**Closed by beerlington** 2019-04-02 02:13 UTC
