### ISSUE TITLE
JaSerializer.Params for relationships

### ISSUE THREAD

**Issue by joshsmith** [vt-elixir/ja_serializer#262] opened 2017-11-30 18:13 UTC
It looks like since `JaSerializer.Params` was originally written, support was added in Ecto for many-to-many relationships.

For example, an `Issue` might have many `labels` and you could `cast_assoc` to create/update those labels alongside your issue.

I'm not certain the serializiation happening here right now matches the ideal input for such a `cast_assoc`. For example, if I passed a `relationships` of `labels`, then the resource identifiers will be iterated over and return `labels_ids`.

Should we be changing this in some way to accommodate what's expected with Ecto?

**Comment by beerlington** [comment] 2017-12-02 01:31
Hi @joshsmith - I've worked a bit with many-to-many relationships in Ecto, and I don't think `relationships` is what you want in this case. My understanding is that `relationships` is for related records that already exist, where you know the id(s) up front.

Looking at the cast_assoc docs, they have an example like this:

```ex
%{"name" => "john doe", "addresses" => [
  %{"street" => "somewhere", "country" => "brazil", "id" => 1},
  %{"street" => "elsewhere", "country" => "poland"},
]}
```
and then

```ex
user
|> Repo.preload(:addresses)
|> Ecto.Changeset.cast(params, [])
|> Ecto.Changeset.cast_assoc(:addresses)
```

If you were trying to reproduce this example, you should be able to pass `addresses` as a regular attribute, like you would with `name`. 

In your case you should be able to pass an attribute called `labels` with a list of label properties.

**Comment by joshsmith** [comment] 2017-12-04 06:06
In this case the `labels` are indeed already created.

I’m fairly certain we’d still be wanting io use the relationships key: http://jsonapi.org/format/#document-resource-object-relationships

The `labels_ids` that are parsed by this module don’t seem like they would play nicely with the m2m operations noted above.

Note that the relationships key is indeed set by my client in this case, which is Ember’s  JSONAPIAdapter, which I’m fairly certain is to spec.

**Comment by begedin** [comment] 2017-12-04 09:48
To argue in favor of what @joshsmith is saying...

What ecto expects is a castable params map, where there isn't really a hierarchical distinction between an attribute and a relationship.

For example

```Elixir
%{
  attr: "foo",
  rel_1_id: 1,
  rel_2: %{
    id: 3,
    attr: "bar",
  }
  rels_3: [
     %{id: 4, attr: "baz"},
     %{attr: "bat"}
  ] 
}
```

`rel_1_id` is valid, and can be used by ecto to associate with a record using `cast` and `assoc_constraint`

`rel_2` is also valid and can be use to cast a `belongs_to` or `has_one` assoc, using `cast_assoc`

`rel_3` is also valid and can be used to cast a `has_many` or `many_to_many`, using also `cast_assoc`. In this case, depending on how the relationship is set up, it could update, replace, create, or throw an error when updating.

The top level `attr` key is just a param for an attribute.

That's what Ecto needs in the params map, and the point of `JaSerializer.Params` is to resolve the differences between what ecto needs and what JSON API specifies.

As far as I can tell, JSON API specifies that relationships go into the `relationships` node of the documents, not `attributes`.

JaSerializer already agrees with this with a `belongs_to`. If se send a `

```JSON
"attributes":  {"foo": "bar"},
"relationships": {"type": "baz", id: 1}
```

as our document, the resulting params map will look like

```Elixir
%{
  "foo" => "bar",
   "baz_id" => "1"
}
```

What your saying now is that, in case of a many to many, we need to send (using the labels example)

```JSON
"attributes":  {
  "foo": "bar",
  "labels": [
    {"type": "label", "id": 1}, 
    {"type": "label", "id": 2}
  ]
},
"relationships": {"type": "baz", "id": 1}
```

IMO, that seems inconsistent.

I could sort of see it if we were dealing with embedded/sideloaded records, but even for that scenario specifically, the JSON API spec seems to tell us the entire embedded record should be in `"relationships"`, not `"attributes"`

**Comment by beerlington** [comment] 2017-12-04 14:41
@begedin my example was for creating new records, not for relating a many to many for existing records. You're correct that the relationships attribute is for this.

@joshsmith I'm a little confused at this point what you're asking for. Are you trying to create new labels with the parent record or are you trying to link to existing labels? Your first question seemed like you were asking about creating new labels, which is what I was responding to. Your second post was talking about labels that are already created.

**Comment by joshsmith** [comment] 2017-12-04 17:22
The latter is what I meant. When I said create originally I meant creating the m2m relationship.

The notes @begedin laid out are precisely the concern.

**Comment by beerlington** [comment] 2017-12-04 18:10
I think I understand the issue now. @begedin Can you point me to where you're seeing that `relationships` should be used for the entire embedded record? All I can find is this http://jsonapi.org/format/#document-resource-object-relationships but that says `relationships` only contains `links`, `data`, and `meta`. That's why I have always used `attributes` when needing to do something with `cast_assoc`.

**Comment by joshsmith** [comment] 2017-12-05 04:02
@beerlington there's a good example listed here: http://jsonapi.org/format/#crud-creating. You can see a photo being created along with its photographer relationship.

> If a relationship is provided in the `relationships` member of the resource object, its value **MUST** be a relationship object with a `data` member. The value of this key represents the linkage the new resource is to have.

See further http://jsonapi.org/format/#crud-updating-resource-relationships

Sorry for spareness of my replies. Trying to update from a cellphone at a remote Army base is not quite ideal. 😝

**Comment by beerlington** [comment] 2017-12-06 02:00
@joshsmith sorry if I confused things along the way. If all you want is to associate existing labels with an issue, you'd need to use `put_assoc` with the `relationships` property, not `cast_assoc`.

You'll have to massage the data a bit to convert it to what `put_assoc` expects, but I think the [Ecto.Changeset docs](https://hexdocs.pm/ecto/Ecto.Changeset.html#cast_assoc/3-alternatives-to-cast_assoc-3) describes that scenario fairly well.

```ex
# params w/ parsed relationships =>
#  %{
#    "labels_ids" => ["1" ,"2", "3"],
#    "other_attr" => "value"
#  }

labels = Repo.all(from l in Label, where: l.id in ^params["labels_ids"])

issue
|> Repo.preload(:labels)
|> Ecto.Changeset.cast(params)
|> Ecto.Changeset.put_assoc(:labels, labels)
```

**Comment by beerlington** [comment] 2019-05-03 11:29
Closing since there isn't anything actionable on here.

**Closed by beerlington** 2019-05-03 11:29 UTC
